language: ruby
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
install:
  - bundle --version
  - bundle install
branches:
  only:
    - master
jobs:
  include:
    - stage: test
      script: rake test
    - stage: release
      if: type != pull_request
      before_install:
        - pip install --user awscli
      script:
        - rake